Develop
GP-Engine-team/gpm pull request #7
Opened 2021-02-24 09:24 UTC by Renardjojo

2021-02-24 09:25 UTC, Korotsu approved these changes

2021-02-24 13:36 UTC, Bad-Sam requested changes

2021-02-24 13:36 UTC, badsami commented on include/GPM/Shape3D/AABB.hpp
> +    }
Consider renaming this method. If I were reading:
```C++
AABB aabb;
Vec3 pt;
bool b = aabb.isInside(pt);
```
I would interpret `b` as: "is the AABB inside the point?"

I'm not sure what the `epsilon` is for here. The interval of comparison will always be large enough to be superior to `epsilon`, since an AABB with `m_iI = 0.f`, `m_iJ = 0.f` or `m_iK = 0.f` is useless

```suggestion
    bool isInside(const Vec3& pt) const noexcept
    {
        const Vec3 localPt{pt - m_center};
        
        return isBetween(localPt.x, -m_iI, m_iI) &&
               isBetween(localPt.y, -m_iJ, m_iJ) &&
               isBetween(localPt.z, -m_iK, m_iK);
    }
```

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/AABB.hpp
> +    float m_iI, m_iJ, m_iK;
All of the data members have getters and setters. I suggest setting them `public`.
I would also suggest changing
```C++
float m_iI, m_iJ, m_iK;
```
to 
```C++
Vec3 bounds;
```

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Random.hpp
> +inline bool ranPercentProba(float percent);
I had to check the implementation to understand what this function was doing. I suggest renaming it in a more explicit way

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Random.inl
> +    return static_cast<T>(rand() % static_cast<T>(2));
```suggestion
    return static_cast<T>(rand() & 1);
```

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Random.hpp
> +inline auto ranged(const T& min, const T& max) -> std::enable_if_t<std::is_integral<T>::value, T>;
```suggestion
inline auto ranged(const T min, const T max) -> std::enable_if_t<std::is_integral<T>::value, T>;
```

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Random.hpp
> +inline auto ranged(const T& min, const T& max) -> std::enable_if_t<std::is_floating_point<T>::value, T>;
```suggestion
inline auto ranged(const T min, const T max) -> std::enable_if_t<std::is_floating_point<T>::value, T>;
```

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Random.inl
> +}
The branches in these functions will probably cost more than doing the actual calculation, even when `max - min <= std::numeric_limits<T>::epsilon()`. I suggest removing the branches, and leaving only the second part of the ternary operations

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Random.inl
> +    float scale = unitValue<float>();
```suggestion
    const float randValue = static_cast<float>(rand());
    const float scale = unitValue<float>();
```

This is *very* minor, but if you feel in the mood of doing optimization, here goes. Same for the other functions which contain unmodified non-const value

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/Capsule.hpp
> +        Sphere RightSphere () const noexcept
The methods names are not to the norm

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/Capsule.hpp
> +        float   m_radius;
I suggest we leave the data members `public`

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/Cylinder.hpp
> +        float   m_radius;
I suggest we leave data members `public`

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/Cylinder.hpp
> +        }
The methods names are not to the norm

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/InfiniteCylinder.hpp
> +        float   m_radius;
I suggest we leave data members `public`

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/Line.hpp
> +                m_normal;
I suggest we leave data members `public`

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/OrientedBox.hpp
> +        float       m_iI {0.f}, m_iJ {0.f}, m_iK {0.f};
I suggest we leave data members `public`

2021-02-24 13:36 UTC, Bad-Sam commented on include/GPM/Shape3D/OrientedBox.hpp
> +        float       m_iI {0.f}, m_iJ {0.f}, m_iK {0.f};
I suggest changing `float m_iI{0.f}, m_iJ{0.f}, m_iK{0.f}` to more explicit names. I suggest `Vec3 bounds`

2021-02-26 10:17 UTC, Bad-Sam approved these changes, later dismissed

2021-03-09 11:01 UTC, Renardjojo commented
I correct majority of optimization. I do not correct the norme probleme with shape only (will be remove when physix will be integer)

2021-03-09 11:01 UTC, merged